name: responsive_svg_icons
description: A wrapping of responsive icons (.svg files), to be used with flutter_svg_icons package.
version: 0.0.1
repository: https://github.com/MohammedAsaadAsaad/responsive_svg_icons

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg_icons: ^0.0.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/s/
    - assets/m/
    - assets/l/